server.port=8080
spring.application.name=CVRgram
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=spidey11453@gmail.com
spring.mail.password=ejqqfqzmoqclvzsl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true